In [ ]:
# NumPy Fundamentals - Student Lab

## Lab Instructions

# Complete all exercises below. Write your code in a Python file or Jupyter notebook. Test each task to ensure it produces the expected output.

# **Assessment Criteria:**
# - Code correctness and functionality
# - Proper use of NumPy functions
# - Code efficiency (use vectorized operations)
# - Clean, readable code with appropriate comments

# ---

## Exercise 1: Array Creation and Attributes (15 points)

### Task 1.1: Create arrays using different methods (10 points)

# Write code to create the following arrays:

# 1. A 1D array containing values from 0 to 9
# 2. A 2D array (3x3) containing values from 1 to 9
# 3. A 3x4 array filled with zeros
# 4. A 2x5 array filled with ones (data type: float32)
# 5. A 4x4 identity matrix
# 6. An array with values from 10 to 50 with step size 5
# 7. An array with 8 evenly spaced values between 0 and 1

# **Your Code:**
# ```python
import numpy as np

# Write your code here

#.arange() to fill the array with the values ranging (from and to)
array_1 = np.arange(0,10)
#.reshape() to change the dimension of the array with the desired cardinality
array_2 = np.arnage(1,10).reshape(3,3)
#.zeroes() to initialize the array with zeroes and can mention the cardinality of the array to be initialized
array_3 = np.zeroes((3,4))
#.ones() to initiliaze the array with ones dtype is used to explicitly mention the datatype of array
array_4 = np.ones((2,5),dtype=np.float32)
#.eyes(n) used to create the identity matrix of size n(n x n cardinality)
array_5 = np.eyes(4)
#.arange() to fill array with values ranging(between first two values in the set) and the last value denoting the incrementation of each value at each iteration
array_6 = np.arange(10,50,5)
#.linspace() to fill the values between a certain range with equal seperation
array_7 = np.linspace(0,1,8)


# ```

### Task 1.2: Explore array attributes (5 points)

Create a 3x4 array with values from 1 to 12. Print the following attributes:
- Shape
- Number of dimensions
- Total number of elements
- Data type
- Item size in bytes
- Total bytes consumed

**Your Code:**
```python
# Write your code here




```

---

## Exercise 2: Indexing and Slicing (20 points)

### Task 2.1: Basic indexing (5 points)

Given the array: `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])`

Write code to:
1. Access the first element
2. Access the last element using negative indexing
3. Access the 5th element

Then create a 2D array with shape (3, 4) and:
- Access the element at row 1, column 2
- Access the element at row 0, column 3
- Access the last element

**Your Code:**
```python
# Write your code here






```

### Task 2.2: Slicing operations (8 points)

Given `arr = np.arange(0, 20)`:

1. Extract elements from index 5 to 15 (inclusive)
2. Extract every 3rd element from the array
3. Reverse the entire array using slicing

Create a 4x4 2D array and:
- Extract the first 2 rows and first 3 columns
- Extract the last 2 rows and last 2 columns
- Extract every other row with all columns

**Your Code:**
```python
# Write your code here







```

### Task 2.3: Boolean and fancy indexing (7 points)

Given `arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])`:

1. Use boolean indexing to extract all values greater than 20
2. Extract all even numbers
3. Extract values between 10 and 30 (inclusive)
4. Use fancy indexing to extract elements at indices 0, 3, 5, and 8

**Your Code:**
```python
# Write your code here





```

---

## Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)

Given two arrays:
- `arr1 = np.array([10, 20, 30, 40, 50])`
- `arr2 = np.array([5, 10, 15, 20, 25])`

Perform the following operations:
1. Element-wise addition
2. Element-wise subtraction
3. Element-wise multiplication
4. Element-wise division
5. Square each element of arr1

Then perform scalar operations on arr1:
- Add 100 to all elements
- Multiply all elements by 3
- Divide all elements by 10

**Your Code:**
```python
# Write your code here









```

### Task 3.2: Universal functions (7 points)

Given `arr = np.array([1, 4, 9, 16, 25, 36])`:

1. Calculate square root of all elements
2. Calculate exponential (e^x) of all elements
3. Calculate natural logarithm of all elements

Create an array of angles `[0, π/6, π/4, π/3, π/2]` and:
- Calculate sine values
- Calculate cosine values

For the array `[1.23, 2.56, 3.89, 4.12]`:
- Round to nearest integer
- Apply floor operation
- Apply ceiling operation

**Your Code:**
```python
# Write your code here









```

---

## Exercise 4: Array Manipulation (20 points)

### Task 4.1: Reshaping and transposing (10 points)

Create an array with values from 1 to 12, then:
1. Reshape it to 3x4
2. Reshape it to 2x6
3. Reshape it to 2x2x3 (3D array)
4. Transpose the 3x4 array
5. Flatten the 3x4 array back to 1D

**Your Code:**
```python
# Write your code here






```

### Task 4.2: Stacking and splitting (10 points)

Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`

1. Stack them vertically to create a 3x3 array
2. Stack them horizontally to create a 1D array

Create an array from 1 to 12 and:
- Split it into 4 equal parts

Create a 4x4 array with values 1-16 and:
- Split it horizontally into 2 parts

**Your Code:**
```python
# Write your code here








```

---

## Exercise 5: Statistical Operations (15 points)

### Task 5.1: Basic statistics (7 points)

Given `arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])`:

Calculate and print:
1. Sum of all elements
2. Mean (average)
3. Median
4. Standard deviation
5. Variance
6. Minimum value
7. Maximum value
8. Index of minimum value
9. Index of maximum value

**Your Code:**
```python
# Write your code here










```

### Task 5.2: Axis-based statistics (8 points)

Create a 3x3 array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```

Calculate:
1. Sum of all elements
2. Sum along axis 0 (column-wise sum)
3. Sum along axis 1 (row-wise sum)
4. Mean along axis 0
5. Mean along axis 1
6. Maximum values along axis 0
7. Maximum values along axis 1

**Your Code:**
```python
# Write your code here








```

---

## Exercise 6: Real-World Application - Student Grade Analysis (25 points)

You are given grade data for 5 students across 4 subjects (Math, Science, English, History):

```python
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])
```

**Tasks:**

1. **Calculate the average grade for each student** (5 points)
   - Output should show Student 1: X.XX, Student 2: Y.YY, etc.

2. **Calculate the average grade for each subject** (5 points)
   - Output: Math: X.XX, Science: Y.YY, etc.

3. **Find the highest and lowest grades in each subject** (5 points)
   - Output for each subject: Highest = X, Lowest = Y

4. **Identify students with an average grade above 85** (3 points)
   - Print student number and their average

5. **Calculate the overall class average** (2 points)
   - Average of all grades across all students

6. **Normalize all grades to a scale of 0-10** (5 points)
   - Use min-max normalization formula: (value - min) / (max - min) * 10
   - Print the normalized grades array

**Bonus:** Identify the top-performing student (+2 points)

**Your Code:**
```python
import numpy as np

grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])

# Write your solution here













```

**Expected Output Format:**
```
--- Task 1: Student Averages ---
Student 1: XX.XX
...

--- Task 2: Subject Averages ---
Math: XX.XX
...

(Continue for all tasks)
```

---

## Exercise 7: Challenge - Sales Data Analysis (30 points)

You are analyzing sales data for a company with 4 products over 6 months:

```python
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])
```

**Tasks:**

1. **Calculate total sales for each product** (5 points)
   - Sum across all months for each product

2. **Calculate total sales for each month** (5 points)
   - Sum across all products for each month (Jan to Jun)

3. **Identify the month with the highest total sales** (4 points)
   - Print the month name and total sales

4. **Calculate the growth rate for each product** (6 points)
   - Growth rate = ((Last month - First month) / First month) × 100
   - Print as percentage for each product

5. **Find products with average monthly sales greater than 120k** (4 points)
   - Calculate average for each product
   - Print products meeting the criteria

6. **Calculate quarter-wise sales** (6 points)
   - Q1: January-March
   - Q2: April-June
   - Print sales for each product in each quarter

**Bonus:** Predict next month (July) sales for each product (+5 points)
- Use a simple method: average of last 2 months + average monthly growth

**Your Code:**
```python
import numpy as np

sales_data = np.array([
    [120, 135, 150, 145, 160, 175],
    [90, 95, 100, 110, 115, 120],
    [150, 145, 155, 160, 170, 180],
    [80, 85, 82, 88, 92, 95]
])

# Write your solution here



















```

---

## Submission Guidelines

1. Complete all exercises in order
2. Test your code to ensure it runs without errors
3. Include comments explaining your logic for complex operations
4. Format your output clearly with appropriate labels
5. Save your file as `numpy_lab_yourname.py` or `numpy_lab_yourname.ipynb`

---

## Evaluation Rubric

| Exercise | Points | Criteria |
|----------|--------|----------|
| Exercise 1 | 15 | Array creation and attributes |
| Exercise 2 | 20 | Indexing and slicing techniques |
| Exercise 3 | 15 | Array operations and ufuncs |
| Exercise 4 | 20 | Array manipulation |
| Exercise 5 | 15 | Statistical operations |
| Exercise 6 | 25 | Real-world application |
| Exercise 7 | 30 | Challenge problem |
| **Total** | **140** | |

**Bonus Points:** Up to +7 additional points available

**Grading Scale:**
- A: 126-140+ points (90%+)
- B: 112-125 points (80-89%)
- C: 98-111 points (70-79%)
- D: 84-97 points (60-69%)
- F: Below 84 points (Below 60%)

---

## Tips for Success

1. **Use vectorized operations** instead of loops whenever possible
2. **Understand the axis parameter**: axis=0 (down columns), axis=1 (across rows)
3. **Check array shapes** frequently to avoid dimension errors
4. **Use meaningful variable names** for clarity
5. **Test incrementally** - don't write all code at once
6. **Read NumPy documentation** when stuck: https://numpy.org/doc/

Good luck!

In [2]:

### Task 1.1: Create arrays using different methods (10 points)

# Write code to create the following arrays:

# 1. A 1D array containing values from 0 to 9
# 2. A 2D array (3x3) containing values from 1 to 9
# 3. A 3x4 array filled with zeros
# 4. A 2x5 array filled with ones (data type: float32)
# 5. A 4x4 identity matrix
# 6. An array with values from 10 to 50 with step size 5
# 7. An array with 8 evenly spaced values between 0 and 1

# **Your Code:**
# ```python
import numpy as np

# Write your code here

#took help of AI for identity matrix, evenly spaced values since still learning as a beginner in python
#.arange() to fill the array with the values ranging from start and to end-1
array_1 = np.arange(0,10)
#.reshape() to change the dimension of the array with the desired cardinality
array_2 = np.arange(1,10).reshape(3,3) #3x3 matrix
#.zeros() to initialize the array with zeroes and can mention the cardinality of the array to be initialized
array_3 = np.zeros((3,4)) #3x4 matrix
#.ones() to initiliaze the array with ones dtype is used to explicitly mention the datatype of array
array_4 = np.ones((2,5),dtype=np.float32) #2x5 matrix
#.eye(n) used to create the identity matrix of size n(n x n cardinality)
array_5 = np.eye(4) #4x4 matrix
#.arange() to fill array with values ranging(between first two values in the set)
# and the last value denoting the incrementation of each value at each iteration
array_6 = np.arange(10,50,5)
#.linspace() to fill specific number of values(8 in this case) between a certain range(0-1)
array_7 = np.linspace(0,1,8)

print(f"Array 1:\n{array_1}")
print(f"Array 2:\n{array_2}")
print(f"Array 3:\n{array_3}")
print(f"Array 4:\n{array_4}")
print(f"Array 5:\n{array_5}")
print(f"Array 6:\n{array_6}")
print(f"Array 7:\n{array_7}")


Array 1:
[0 1 2 3 4 5 6 7 8 9]
Array 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 3:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 4:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array 5:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array 6:
[10 15 20 25 30 35 40 45]
Array 7:
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [4]:
### Task 1.2: Explore array attributes (5 points)

# Create a 3x4 array with values from 1 to 12. Print the following attributes:
# - Shape
# - Number of dimensions
# - Total number of elements
# - Data type
# - Item size in bytes
# - Total bytes consumed

# **Your Code:**
# ```python
# Write your code here
import numpy as np

# filled array with the values from 1 to 12 and converted this 1D array into 3x4 array
array = np.arange(1, 13).reshape(3, 4)

print(f"Array:\n{array}")

print("\nShape:", array.shape)                 # rows x columns - > shape (cardinality)
print("Dimensions:", array.ndim)               # number of axes -> .ndim (gives the dimension)
print("Total elements:", array.size)           # count of values in array-> .size
print("Data type:", array.dtype)               # datatype of ele in array -> .dtype
print("Item size (bytes):", array.itemsize)    # bytes per element -> .itemsize
print("Total bytes:", array.nbytes)            # total memory used -> .nbytes ( bytes per ele x count of values)


Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Dimensions: 2
Total elements: 12
Data type: int64
Item size (bytes): 8
Total bytes: 96


In [13]:
## Exercise 2: Indexing and Slicing (20 points)

### Task 2.1: Basic indexing (5 points)

# Write code to:
# 1. Access the first element
# 2. Access the last element using negative indexing
# 3. Access the 5th element

# Then create a 2D array with shape (3, 4) and:
# - Access the element at row 1, column 2
# - Access the element at row 0, column 3
# - Access the last element

# **Your Code:**
# ```python

import numpy as np

# Given 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Basic indexing
first_element = arr[0] # index starts at 0
last_element = arr[-1] # negative index gives last ele in array
fifth_element = arr[4]

print("First element:", first_element)
print("Last element:", last_element)
print("Fifth element:", fifth_element)

# Create a 3x4 array
array_2d = np.arange(1,13).reshape(3, 4)

print("\n2D Array:")
print(array_2d)

# Accessing elements in 2D array
ele_row1_col2 = array_2d[1, 2]     # row 1, column 2
ele_row0_col3 = array_2d[0, 3]     # row 0, column 3
last_ele_2d = array_2d[-1, -1]     # last element

print("\nElement at row 1, col 2:", ele_row1_col2)
print("Element at row 0, col 3:", ele_row0_col3)
print("Last element in 2D array:", last_ele_2d)

First element: 10
Last element: 100
Fifth element: 50

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at row 1, col 2: 7
Element at row 0, col 3: 4
Last element in 2D array: 12


In [16]:
### Task 2.2: Slicing operations (8 points)
import numpy as np

# **Your Code:**
# ```python
# Write your code here

# Given
arr = np.arange(0, 20)
# 1. Extract elements from index 5 to 15 (inclusive)
subarray_1 = arr[5:16]
# 2. Extract every 3rd element from the array
subarray_2 = arr[::3] # -> begins from 0th index
# 3. Reverse the entire array using slicing
subarray_3 = arr[::-1]

print(f"Array: \n{arr}")

print("\nElements 5 to 15:", subarray_1)
print("\nEvery 3rd element:", subarray_2)
print("\nReversed array:", subarray_3)

# Create a 4x4 2D array and:
array_2 = np.arange(1,17).reshape(4,4) # 4x4 => 16 elements (from 1 to (17-1))
print(f"\nArray: \n{array_2}")
# used AI for syntax of slicing operations since it is not 1D array
# - Extract the first 2 rows and first 3 columns
subarray_4 = array_2[:2,:3]
# - Extract the last 2 rows and last 2 columns
subarray_5 = array_2[:-2:-2]
# - Extract every other row with all columns
subarray_6 = array_2[:2,:] # every other row -> skip one after the other but all columns of that row starting from 0th row

print("\nFirst 2 rows & first 3 cols:\n", subarray_4)
print("\nLast 2 rows & last 2 cols:\n", subarray_5)
print("\nEvery other row:\n", subarray_6)

Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Elements 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]

Every 3rd element: [ 0  3  6  9 12 15 18]

Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First 2 rows & first 3 cols:
 [[1 2 3]
 [5 6 7]]

Last 2 rows & last 2 cols:
 [[13 14 15 16]]

Every other row:
 [[1 2 3 4]
 [5 6 7 8]]


In [22]:
### Task 2.3: Boolean and fancy indexing (7 points)


# **Your Code:**
# ```python
# Write your code here

# Given
arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])
# 1. Use boolean indexing to extract all values greater than 20
greater_20 = arr[arr > 20]
# 2. Extract all even numbers
even_ele = arr[arr%2==0]
# 3. Extract values between 10 and 30 (inclusive)
between_10_30 = arr[(arr>=10) & (arr<=30)]
# 4. Use fancy indexing to extract elements at indices 0, 3, 5, and 8
fancy_indx = arr[[0,3,5,8]]

print("Array:",arr)
print("\nGreater than 20:", greater_20)
print("\nEven numbers:", even_ele)
print("\nBetween 10 and 30:", between_10_30)
print("\nFancy indexing result:", subarray_4)

Array: [15 23  8 42 11 37 19  5 33 28]

Greater than 20: [23 42 37 33 28]

Even numbers: [ 8 42 28]

Between 10 and 30: [15 23 11 19 28]

Fancy indexing result: [15 42 37 33]


In [26]:

## Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)



# Then perform scalar operations on arr1:
# - Add 100 to all elements
# - Multiply all elements by 3
# - Divide all elements by 10

# **Your Code:**
# ```python
# Write your code here

# Given two arrays:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 10, 15, 20, 25])
print("Array 1: ",arr1)
print("Array 2: ",arr2)
# Perform the following operations:

# 1. Element-wise addition
add = arr1 + arr2
# 2. Element-wise subtraction
sub = arr1 - arr2
# 3. Element-wise multiplication
mul = arr1 * arr2
# 4. Element-wise division
div = arr1 / arr2
# 5. Square each element of arr1
square = arr1 ** 2

print("\nAddition:", add)
print("\nSubtraction:", sub)
print("\nMultiplication:", mul)
print("\nDivision:", div)
print("\nSquare of arr1:", square)

# Scalar operations on arr1 => scalar operations in Numpy follow vectorization
add_scalar = arr1 + 100
mul_scalar = arr1 * 3
div_scalar = arr1 / 10

print("\nAdd 100:", add_scalar)
print("\nMultiply by 3:", mul_scalar)
print("\nDivide by 10:", div_scalar)


Array 1:  [10 20 30 40 50]
Array 2:  [ 5 10 15 20 25]

Addition: [15 30 45 60 75]

Subtraction: [ 5 10 15 20 25]

Multiplication: [  50  200  450  800 1250]

Division: [2. 2. 2. 2. 2.]

Square of arr1: [ 100  400  900 1600 2500]

Add 100: [110 120 130 140 150]

Multiply by 3: [ 30  60  90 120 150]

Divide by 10: [1. 2. 3. 4. 5.]


In [29]:
### Task 3.2: Universal functions (7 points)

# 1. Calculate square root of all elements
# 2. Calculate exponential (e^x) of all elements
# 3. Calculate natural logarithm of all elements

# - Calculate sine values
# - Calculate cosine values

# - Round to nearest integer
# - Apply floor operation
# - Apply ceiling operation

# **Your Code:**
# ```python
# Write your code here

# Given
arr = np.array([1, 4, 9, 16, 25, 36])
print("Array:",arr)
# 1. Square root (x^2)
sqrt = np.sqrt(arr)

# 2. Exponential (e^x)
exp = np.exp(arr)

# 3. Natural log (ln x)
log = np.log(arr)

print("\nSquare root:", sqrt)
print("\nExponential:", exp)
print("\nNatural log:", log)


# Angles in radians
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Sine and cosine
sin = np.sin(angles)
cos = np.cos(angles)

print("\nAngles (radians):", angles)
print("Sine values:", sin)
print("Cosine values:", cos)

#Given
nums = np.array([1.23, 2.56, 3.89, 4.12])

rounded = np.rint(nums)      # round to nearest integer -> used ai doesn't know this function
floored = np.floor(nums)     # round down
ceiled  = np.ceil(nums)      # round up

print("\nOriginal numbers:", nums)
print("Rounded:", rounded)
print("Floor:", floored)
print("Ceil:", ceiled)


Array: [ 1  4  9 16 25 36]

Square root: [1. 2. 3. 4. 5. 6.]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]

Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]

Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Original numbers: [1.23 2.56 3.89 4.12]
Rounded: [1. 3. 4. 4.]
Floor: [1. 2. 3. 4.]
Ceil: [2. 3. 4. 5.]


In [30]:
## Exercise 4: Array Manipulation (20 points)

### Task 4.1: Reshaping and transposing (10 points)

# **Your Code:**
# ```python
# Write your code here

# Create an array with values from 1 to 12
arr = np.arange(1, 13)

# 1. Reshape to 3x4
arr_3x4 = arr.reshape(3, 4)

# 2. Reshape to 2x6
arr_2x6 = arr.reshape(2, 6)

# 3. Reshape to 2x2x3 (3D array)
arr_3d = arr.reshape(2, 2, 3)

# 4. Transpose the 3x4 array (swap rows & columns)
arr_transposed = arr_3x4.T #.T -> transposes the matrix(arr)

# 5. Flatten the 3x4 array back to 1D
arr_flat = arr_3x4.flatten()

print("Original array:", arr)
print("\n3x4 array:\n", arr_3x4)
print("\n2x6 array:\n", arr_2x6)
print("\n2x2x3 array (3D):\n", arr_3d)
print("\nTransposed 3x4 array:\n", arr_transposed)
print("\nFlattened array:", arr_flat)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

2x2x3 array (3D):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 3x4 array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
### Task 4.2: Stacking and splitting (10 points)


# **Your Code:**
# ```python
# Write your code here

import numpy as np

# Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# 1. Stack vertically -> 3x3 matrix
vertical_stack = np.vstack((a, b, c))

# 2. Stack horizontally -> join into one 1D array
horizontal_stack = np.hstack((a, b, c))

print("Vertical Stack (3x3):\n", vertical_stack)
print("\nHorizontal Stack (1D):", horizontal_stack)


# 3. Split array 1 to 12 into 4 equal parts
arr = np.arange(1, 13)
split_arr = np.split(arr, 4) #used AI for the syntax

print("\nArray split into 4 parts:")
for part in split_arr:
    print(part)


# Create 4x4 array (1–16)
arr_4x4 = np.arange(1, 17).reshape(4, 4)

# Split horizontally into 2 parts (along rows)
horizontal_split = np.vsplit(arr_4x4, 2) #used AI for syntax

print("\n4x4 Array:\n", arr_4x4)
print("\nArray Horizontal split into 2 parts:")
for part in horizontal_split:
    print(part)


Vertical Stack (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal Stack (1D): [1 2 3 4 5 6 7 8 9]

Array split into 4 parts:
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array Horizontal split into 2 parts:
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [34]:
## Exercise 5: Statistical Operations (15 points)

### Task 5.1: Basic statistics (7 points)


# Calculate and print:
# 1. Sum of all elements
# 2. Mean (average)
# 3. Median
# 4. Standard deviation
# 5. Variance
# 6. Minimum value
# 7. Maximum value
# 8. Index of minimum value
# 9. Index of maximum value

# **Your Code:**
# ```python
# Write your code here

# Given
arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])

total_sum = np.sum(arr) # sum of array ele
mean = np.mean(arr) # mean(avg) = sum of ele/total no of ele
median = np.median(arr) # median of the array
std = np.std(arr) # standard deviation
var = np.var(arr) # variance
min = np.min(arr) #min ele in array
max = np.max(arr) # max ele in array
min_indx = np.argmin(arr) # index of min value
max_indx = np.argmax(arr) # index of max value

print("Sum:", total_sum)
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std)
print("Variance:", var)
print("Minimum value:", min)
print("Maximum value:", max)
print("Index of minimum value:", min_indx)
print("Index of maximum value:", max_indx)

Sum: 525
Mean: 52.5
Median: 50.5
Standard deviation: 26.424420523447623
Variance: 698.25
Minimum value: 12
Maximum value: 90
Index of minimum value: 0
Index of maximum value: 8


In [35]:
### Task 5.2: Axis-based statistics (8 points)

# Calculate:
# 1. Sum of all elements
# 2. Sum along axis 0 (column-wise sum)
# 3. Sum along axis 1 (row-wise sum)
# 4. Mean along axis 0
# 5. Mean along axis 1
# 6. Maximum values along axis 0
# 7. Maximum values along axis 1

# **Your Code:**
# ```python
# Write your code here

# Create 3x3 array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 1. Sum of all elements
total_sum = np.sum(arr)

# 2. Column-wise sum (axis=0)
sum_axis0 = np.sum(arr, axis=0)

# 3. Row-wise sum (axis=1)
sum_axis1 = np.sum(arr, axis=1)

# 4. Column-wise mean
mean_axis0 = np.mean(arr, axis=0)

# 5. Row-wise mean
mean_axis1 = np.mean(arr, axis=1)

# 6. Max along columns
max_axis0 = np.max(arr, axis=0)

# 7. Max along rows
max_axis1 = np.max(arr, axis=1)

print("Total sum:", total_sum)
print("Sum along axis 0 (columns):", sum_axis0)
print("Sum along axis 1 (rows):", sum_axis1)
print("Mean along axis 0:", mean_axis0)
print("Mean along axis 1:", mean_axis1)
print("Max along axis 0:", max_axis0)
print("Max along axis 1:", max_axis1)

Total sum: 450
Sum along axis 0 (columns): [120 150 180]
Sum along axis 1 (rows): [ 60 150 240]
Mean along axis 0: [40. 50. 60.]
Mean along axis 1: [20. 50. 80.]
Max along axis 0: [70 80 90]
Max along axis 1: [30 60 90]


In [41]:
## Exercise 6: Real-World Application - Student Grade Analysis (25 points)

# You are given grade data for 5 students across 4 subjects (Math, Science, English, History):

# ```python
# grades = np.array([
#     [85, 90, 78, 88],
#     [92, 88, 95, 90],
#     [76, 82, 80, 75],
#     [88, 85, 90, 92],
#     [95, 92, 88, 94]
# ])
# ```

# **Tasks:**

# 1. **Calculate the average grade for each student** (5 points)
#    - Output should show Student 1: X.XX, Student 2: Y.YY, etc.

# 2. **Calculate the average grade for each subject** (5 points)
#    - Output: Math: X.XX, Science: Y.YY, etc.

# 3. **Find the highest and lowest grades in each subject** (5 points)
#    - Output for each subject: Highest = X, Lowest = Y

# 4. **Identify students with an average grade above 85** (3 points)
#    - Print student number and their average

# 5. **Calculate the overall class average** (2 points)
#    - Average of all grades across all students

# 6. **Normalize all grades to a scale of 0-10** (5 points)
#    - Use min-max normalization formula: (value - min) / (max - min) * 10
#    - Print the normalized grades array

# **Bonus:** Identify the top-performing student (+2 points)

# **Your Code:**
# ```python
import numpy as np

grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])

# Write your solution here

# 1. Average grade for each student (row-wise mean)
students_avgs = np.mean(grades, axis=1)

print("Average grade per student:")
i = 1
for avg in students_avgs:
    print(f"Student {i}: {avg:.2f}")
    i = i+1

# 2. Average grade for each subject (column-wise mean)
subjects_avgs = np.mean(grades, axis=0)
# for the given subjects Math, Science, English, History
subjects = ["Math", "Science", "English", "History"]
print("\nAverage grade per subject:")
for name, avg in zip(subjects, subjects_avgs): #here zip combines the two things subjects and the students avgs for the subjects
    print(f"{name}: {avg:.2f}")
# 3. Highest and lowest grade in each subject
subject_max = np.max(grades, axis=0) # subject => column wise axis = 0, students => row wise axis =1
subject_min = np.min(grades, axis=0)

print("\nHighest and lowest grades per subject:")
for name, hi, lo in zip(subjects, subject_max, subject_min): # here zip combines the subjects and corresponding max and min values
    print(f"{name}: Highest = {hi}, Lowest = {lo}")

# 4. Students with average above 85
print("\nStudents with average above 85:")
i = 1
for avg in students_avgs:
    if avg > 85:
        print(f"Student {i}: {avg:.2f}")
    i = i+1

# 5. Overall class average (all grades)
class_average = np.mean(grades)
print(f"\nOverall class average: {class_average:.2f}")

# 6. Normalize grades to 0–10 scale using min-max normalization
min = np.min(grades)
max = np.max(grades)

normalized_grades = (grades - min) / (max - min) * 10
print("\nNormalized grades (0–10 scale):")
print(normalized_grades)

# Bonus: Top-performing student (highest average)
top_student = np.argmax(students_avgs) + 1   # used AI to know how to get the index of the a certain value(in this case it's max hence argmax)
                                           # +1 since the indexing starts from 0
print(f"\nTop performing student: Student {top_student}")

Average grade per student:
Student 1: 85.25
Student 2: 91.25
Student 3: 78.25
Student 4: 88.75
Student 5: 92.25

Average grade per subject:
Math: 87.20
Science: 87.40
English: 86.20
History: 87.80

Highest and lowest grades per subject:
Math: Highest = 95, Lowest = 76
Science: Highest = 92, Lowest = 82
English: Highest = 95, Lowest = 78
History: Highest = 94, Lowest = 75

Students with average above 85:
Student 1: 85.25
Student 2: 91.25
Student 4: 88.75
Student 5: 92.25

Overall class average: 87.15

Normalized grades (0–10 scale):
[[ 5.   7.5  1.5  6.5]
 [ 8.5  6.5 10.   7.5]
 [ 0.5  3.5  2.5  0. ]
 [ 6.5  5.   7.5  8.5]
 [10.   8.5  6.5  9.5]]

Top performing student: Student 5


In [43]:

## Exercise 7: Challenge - Sales Data Analysis (30 points)

# You are analyzing sales data for a company with 4 products over 6 months:

# ```python
# sales_data = np.array([
#     [120, 135, 150, 145, 160, 175],  # Product A
#     [90, 95, 100, 110, 115, 120],    # Product B
#     [150, 145, 155, 160, 170, 180],  # Product C
#     [80, 85, 82, 88, 92, 95]         # Product D
# ])
# ```

# **Tasks:**

# 1. **Calculate total sales for each product** (5 points)
#    - Sum across all months for each product

# 2. **Calculate total sales for each month** (5 points)
#    - Sum across all products for each month (Jan to Jun)

# 3. **Identify the month with the highest total sales** (4 points)
#    - Print the month name and total sales

# 4. **Calculate the growth rate for each product** (6 points)
#    - Growth rate = ((Last month - First month) / First month) × 100
#    - Print as percentage for each product

# 5. **Find products with average monthly sales greater than 120k** (4 points)
#    - Calculate average for each product
#    - Print products meeting the criteria

# 6. **Calculate quarter-wise sales** (6 points)
#    - Q1: January-March
#    - Q2: April-June
#    - Print sales for each product in each quarter

# **Bonus:** Predict next month (July) sales for each product (+5 points)
# - Use a simple method: average of last 2 months + average monthly growth

# **Your Code:**
# ```python
import numpy as np

sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])

products = ["Product A", "Product B", "Product C", "Product D"]
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

# 1. Total sales per product (row-wise sum) => axis 1
total_per_product = np.sum(sales_data, axis=1)
print("Total sales per product:")
for p, total in zip(products, total_per_product):
    print(f"{p}: {total}")

# 2. Total sales per month (column-wise sum) => axis 0
total_per_month = np.sum(sales_data, axis=0)
print("\nTotal sales per month:")
for m, total in zip(months, total_per_month):
    print(f"{m}: {total}")

# 3. Month with highest total sales
max_month_index = np.argmax(total_per_month) # argmax returns the index of the highest value in matrix
print(f"\nHighest total sales month: {months[max_month_index]} "
      f"({total_per_month[max_month_index]})")

# 4. Growth rate for each product
first_month = sales_data[:, 0] # [:,x] -> all rows but xth column ( here all products(rows) at first month(0th col))
last_month = sales_data[:, -1] #likewise for the last month(Jun)
growth_rate = ((last_month - first_month) / first_month) * 100

print("\nGrowth rate per product (%):")
for p, g in zip(products, growth_rate):
    print(f"{p}: {g:.2f}%")

# 5. Products with average monthly sales > 120
avg_sales = np.mean(sales_data, axis=1)
print("\nProducts with average monthly sales > 120k:")
for p, avg in zip(products, avg_sales):
    if avg > 120:
        print(f"{p}: {avg:.2f}")

# 6. Quarter-wise sales
q1 = np.sum(sales_data[:, 0:3], axis=1)   # Jan–Mar
q2 = np.sum(sales_data[:, 3:6], axis=1)   # Apr–Jun

print("\nQuarter-wise sales:")
i = 0
for p in products:
    print(f"{p} — Q1: {q1[i]}, Q2: {q2[i]}")
    i=i+1

# BONUS — Predict July sales
# Method: (avg of last 2 months) + (average monthly growth)

last_two_avg = np.mean(sales_data[:, -2:], axis=1) # : => indicate all products , -2: => indicate from the last 2 months
monthly_growth = (sales_data[:, -1] - sales_data[:, -2])  # growth from May->Jun

july_prediction = last_two_avg + monthly_growth

print("\nPredicted July sales (simple model):")
for p, pred in zip(products, july_prediction):
    print(f"{p}: {pred:.2f}")


Total sales per product:
Product A: 885
Product B: 630
Product C: 960
Product D: 522

Total sales per month:
Jan: 440
Feb: 460
Mar: 487
Apr: 503
May: 537
Jun: 570

Highest total sales month: Jun (570)

Growth rate per product (%):
Product A: 45.83%
Product B: 33.33%
Product C: 20.00%
Product D: 18.75%

Products with average monthly sales > 120k:
Product A: 147.50
Product C: 160.00

Quarter-wise sales:
Product A — Q1: 405, Q2: 480
Product B — Q1: 285, Q2: 345
Product C — Q1: 450, Q2: 510
Product D — Q1: 247, Q2: 275

Predicted July sales (simple model):
Product A: 182.50
Product B: 122.50
Product C: 185.00
Product D: 96.50
